export declare const languages: {
    en: {
        code: string;
        name: string;
        flag: string;
        locale: string;
    };
    fi: {
        code: string;
        name: string;
        flag: string;
        locale: string;
    };
};
export declare function getLanguageFromPath(pathname: any): "en" | "fi";
export declare function getOppositeLanguage(lang: any): "en" | "fi";
export declare function getLanguagePrefix(lang: any): "" | "/fi";
export declare function getLocalizedUrl(pathname: any, targetLang: any): any;
export declare const translations: {
    en: {
        home: string;
        services: string;
        packages: string;
        industries: string;
        resources: string;
        about: string;
        contact: string;
        contactUs: string;
        learnMore: string;
        getStarted: string;
        freeConsultation: string;
        noObligation: string;
        heroTitle: string;
        heroSubtitle: string;
        heroPrimaryCTA: string;
        heroSecondaryCTA: string;
        servicesTitle: string;
        servicesDescription: string;
        footerTagline: string;
        regulatoryComplianceTitle: string;
        regulatoryComplianceTagline: string;
        riskAndAssessmentTitle: string;
        riskAndAssessmentTagline: string;
        readMore: string;
        nis2ComplianceTitle: string;
        nis2ComplianceDesc: string;
        doraComplianceTitle: string;
        doraComplianceDesc: string;
        gdprPrivacyTitle: string;
        gdprPrivacyDesc: string;
        eidasDigitalTrustTitle: string;
        eidasDigitalTrustDesc: string;
        eprivacyCookieTitle: string;
        eprivacyCookieDesc: string;
        riskAssessmentsTitle: string;
        riskAssessmentsDesc: string;
        riskManagementTitle: string;
        riskManagementDesc: string;
        thirdPartyRiskTitle: string;
        thirdPartyRiskDesc: string;
    };
    fi: {
        home: string;
        services: string;
        packages: string;
        industries: string;
        resources: string;
        about: string;
        contact: string;
        contactUs: string;
        learnMore: string;
        getStarted: string;
        freeConsultation: string;
        noObligation: string;
        heroTitle: string;
        heroSubtitle: string;
        heroPrimaryCTA: string;
        heroSecondaryCTA: string;
        servicesTitle: string;
        servicesDescription: string;
        footerTagline: string;
        regulatoryComplianceTitle: string;
        regulatoryComplianceTagline: string;
        riskAndAssessmentTitle: string;
        riskAndAssessmentTagline: string;
        readMore: string;
        nis2ComplianceTitle: string;
        nis2ComplianceDesc: string;
        doraComplianceTitle: string;
        doraComplianceDesc: string;
        gdprPrivacyTitle: string;
        gdprPrivacyDesc: string;
        eidasDigitalTrustTitle: string;
        eidasDigitalTrustDesc: string;
        eprivacyCookieTitle: string;
        eprivacyCookieDesc: string;
        riskAssessmentsTitle: string;
        riskAssessmentsDesc: string;
        riskManagementTitle: string;
        riskManagementDesc: string;
        thirdPartyRiskTitle: string;
        thirdPartyRiskDesc: string;
    };
};
export declare function t(key: any, lang?: string): any;
//# sourceMappingURL=language.d.ts.map